db.driverClassName=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/opening_cms?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_unicode_ci&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
db.username=root
db.password=123456

db.initialSize=5
db.maxActive=20
db.minIdle=5
db.maxWait=60000
db.timeBetweenEvictionRunsMillis=60000
db.minEvictableIdleTimeMillis=300000
db.validationQuery=SELECT 1
db.testWhileIdle=true
db.testOnBorrow=false
db.testOnReturn=false
db.poolPreparedStatements=true
db.maxPoolPreparedStatementPerConnectionSize=20
db.filters=stat,wall,log4j
db.connectionInitSqls=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
